// config/museums.ts
// Catálogo semilla de la colección C. Es una lista curada A MANO, y esa es la
// clave de todo el apartado: los museos NO entran por consenso ni superan el
// umbral de 62 puntos — entran porque están aquí (§5.1, «la excepción de los
// museos»). Meter o sacar uno es una decisión editorial explícita: una línea en
// este archivo, revisada en un PR.
//
// Cada entrada aporta lo que NO se puede extraer con fiabilidad: identidad
// estable (`slug`), web oficial y coordenadas. Horarios, precios, gratuidades y
// exposición vigente se extraen de forma determinista en cada refresco semanal
// (§6.6); NO se escriben aquí, porque los escribe la máquina.
import type { MuseumSeed } from './schema'

type Seed = Omit<MuseumSeed, 'municipality' | 'tags' | 'enabled'> &
  Partial<Pick<MuseumSeed, 'municipality' | 'tags' | 'enabled'>>

export const MUSEUMS: Seed[] = [
  // ── Ciutat Vella ────────────────────────────────────────────────────────
  { slug: 'museu-picasso', name: 'Museu Picasso',
    officialUrl: 'https://www.museupicasso.bcn.cat/',
    hoursUrl: 'https://www.museupicasso.bcn.cat/es/horarios-y-precios',
    ticketsUrl: 'https://www.museupicasso.bcn.cat/es/entradas',
    address: 'Carrer de Montcada, 15-23, 08003 Barcelona',
    lat: 41.385228, lng: 2.180968, zipCode: '08003',
    neighborhood: 'Sant Pere, Santa Caterina i la Ribera', district: 'Ciutat Vella',
    tags: ['arte', 'picasso'] },

  { slug: 'macba', name: 'MACBA · Museu d’Art Contemporani de Barcelona',
    officialUrl: 'https://www.macba.cat/',
    address: 'Plaça dels Àngels, 1, 08001 Barcelona',
    lat: 41.383056, lng: 2.166667, zipCode: '08001',
    neighborhood: 'El Raval', district: 'Ciutat Vella',
    tags: ['arte-contemporaneo'] },

  { slug: 'cccb', name: 'CCCB · Centre de Cultura Contemporània de Barcelona',
    officialUrl: 'https://www.cccb.org/',
    address: 'Carrer de Montalegre, 5, 08001 Barcelona',
    lat: 41.383333, lng: 2.167222, zipCode: '08001',
    neighborhood: 'El Raval', district: 'Ciutat Vella',
    tags: ['exposiciones', 'cultura-contemporanea'] },

  { slug: 'museu-maritim-de-barcelona', name: 'Museu Marítim de Barcelona',
    officialUrl: 'https://www.mmb.cat/',
    address: 'Av. de les Drassanes, s/n, 08001 Barcelona',
    lat: 41.375278, lng: 2.176111, zipCode: '08001',
    neighborhood: 'El Raval', district: 'Ciutat Vella',
    tags: ['historia', 'mar'] },

  { slug: 'museu-frederic-mares', name: 'Museu Frederic Marès',
    officialUrl: 'https://www.museumares.bcn.cat/',
    address: 'Plaça de Sant Iu, 5, 08002 Barcelona',
    lat: 41.383889, lng: 2.176389, zipCode: '08002',
    neighborhood: 'El Gòtic', district: 'Ciutat Vella',
    tags: ['escultura', 'coleccion'] },

  { slug: 'muhba-placa-del-rei', name: 'MUHBA Plaça del Rei',
    officialUrl: 'https://www.barcelona.cat/museuhistoria/',
    address: 'Plaça del Rei, s/n, 08002 Barcelona',
    lat: 41.383611, lng: 2.177500, zipCode: '08002',
    neighborhood: 'El Gòtic', district: 'Ciutat Vella',
    tags: ['historia', 'arqueologia'] },

  { slug: 'el-born-centre-de-cultura-i-memoria', name: 'El Born Centre de Cultura i Memòria',
    officialUrl: 'https://elbornculturaimemoria.barcelona.cat/',
    address: 'Plaça Comercial, 12, 08003 Barcelona',
    lat: 41.385278, lng: 2.183056, zipCode: '08003',
    neighborhood: 'Sant Pere, Santa Caterina i la Ribera', district: 'Ciutat Vella',
    tags: ['historia', 'yacimiento'] },

  { slug: 'museu-de-cultures-del-mon', name: 'Museu de Cultures del Món',
    officialUrl: 'https://museuculturesmon.bcn.cat/',
    address: 'Carrer de Montcada, 12, 08003 Barcelona',
    lat: 41.384722, lng: 2.181111, zipCode: '08003',
    neighborhood: 'Sant Pere, Santa Caterina i la Ribera', district: 'Ciutat Vella',
    tags: ['etnografia'] },

  { slug: 'palau-guell', name: 'Palau Güell',
    officialUrl: 'https://inicio.palauguell.cat/',
    address: 'Carrer Nou de la Rambla, 3-5, 08001 Barcelona',
    lat: 41.379167, lng: 2.174444, zipCode: '08001',
    neighborhood: 'El Raval', district: 'Ciutat Vella',
    tags: ['gaudi', 'modernismo'] },

  { slug: 'palau-de-la-musica-catalana', name: 'Palau de la Música Catalana',
    officialUrl: 'https://www.palaumusica.cat/',
    address: 'C/ Palau de la Música, 4-6, 08003 Barcelona',
    lat: 41.387500, lng: 2.175278, zipCode: '08003',
    neighborhood: 'Sant Pere, Santa Caterina i la Ribera', district: 'Ciutat Vella',
    tags: ['modernismo', 'arquitectura'] },

  { slug: 'museu-de-la-xocolata', name: 'Museu de la Xocolata',
    officialUrl: 'https://www.museuxocolata.cat/',
    address: 'Carrer del Comerç, 36, 08003 Barcelona',
    lat: 41.387778, lng: 2.181667, zipCode: '08003',
    neighborhood: 'Sant Pere, Santa Caterina i la Ribera', district: 'Ciutat Vella',
    tags: ['familiar', 'gastronomia'] },

  { slug: 'meam-museu-europeu-art-modern', name: 'MEAM · Museu Europeu d’Art Modern',
    officialUrl: 'https://meam.es/',
    address: 'Carrer de la Barra de Ferro, 5, 08003 Barcelona',
    lat: 41.385833, lng: 2.180000, zipCode: '08003',
    neighborhood: 'Sant Pere, Santa Caterina i la Ribera', district: 'Ciutat Vella',
    tags: ['arte-figurativo'] },

  { slug: 'moco-museum-barcelona', name: 'Moco Museum Barcelona',
    officialUrl: 'https://mocomuseum.com/barcelona',
    address: 'Carrer de Montcada, 25, 08003 Barcelona',
    lat: 41.385556, lng: 2.181389, zipCode: '08003',
    neighborhood: 'Sant Pere, Santa Caterina i la Ribera', district: 'Ciutat Vella',
    tags: ['arte-contemporaneo', 'street-art'] },

  { slug: 'museu-de-cera-de-barcelona', name: 'Museu de Cera de Barcelona',
    officialUrl: 'https://www.museocerabcn.com/',
    address: 'Passatge de la Banca, 7, 08002 Barcelona',
    lat: 41.377778, lng: 2.175278, zipCode: '08002',
    neighborhood: 'El Gòtic', district: 'Ciutat Vella',
    tags: ['familiar'] },

  { slug: 'museu-de-la-moto-de-barcelona', name: 'Museu de la Moto de Barcelona',
    officialUrl: 'https://www.museumoto.com/',
    address: 'Carrer de la Palla, 10, 08002 Barcelona',
    lat: 41.383333, lng: 2.174167, zipCode: '08002',
    neighborhood: 'El Gòtic', district: 'Ciutat Vella',
    tags: ['motor'] },

  { slug: 'miba-museu-idees-i-invents', name: 'MIBA · Museu d’Idees i Invents de Barcelona',
    officialUrl: 'https://mibamuseum.com/',
    address: 'Carrer de la Ciutat, 7, 08002 Barcelona',
    lat: 41.382222, lng: 2.177222, zipCode: '08002',
    neighborhood: 'El Gòtic', district: 'Ciutat Vella',
    tags: ['familiar', 'diseno'] },

  { slug: 'arts-santa-monica', name: 'Arts Santa Mònica',
    officialUrl: 'https://artssantamonica.gencat.cat/',
    address: 'La Rambla, 7, 08002 Barcelona',
    lat: 41.377222, lng: 2.177778, zipCode: '08002',
    neighborhood: 'El Raval', district: 'Ciutat Vella',
    tags: ['arte-contemporaneo', 'gratis'] },

  { slug: 'la-virreina-centre-de-la-imatge', name: 'La Virreina Centre de la Imatge',
    officialUrl: 'https://ajuntament.barcelona.cat/lavirreina/',
    address: 'La Rambla, 99, 08002 Barcelona',
    lat: 41.381111, lng: 2.171944, zipCode: '08002',
    neighborhood: 'El Raval', district: 'Ciutat Vella',
    tags: ['fotografia', 'gratis'] },

  { slug: 'museu-hash-marihuana-cannabis', name: 'Hash Marihuana & Hemp Museum',
    officialUrl: 'https://hashmuseum.com/es/barcelona',
    address: 'Carrer Ample, 35, 08002 Barcelona',
    lat: 41.379722, lng: 2.180278, zipCode: '08002',
    neighborhood: 'El Gòtic', district: 'Ciutat Vella',
    tags: ['coleccion'], enabled: false },

  // ── Eixample ────────────────────────────────────────────────────────────
  { slug: 'la-pedrera-casa-mila', name: 'La Pedrera · Casa Milà',
    officialUrl: 'https://www.lapedrera.com/',
    address: 'Provença, 261-265, 08008 Barcelona',
    lat: 41.395278, lng: 2.161944, zipCode: '08008',
    neighborhood: 'La Dreta de l’Eixample', district: 'Eixample',
    tags: ['gaudi', 'modernismo'] },

  { slug: 'casa-batllo', name: 'Casa Batlló',
    officialUrl: 'https://www.casabatllo.es/',
    address: 'Passeig de Gràcia, 43, 08007 Barcelona',
    lat: 41.391667, lng: 2.164722, zipCode: '08007',
    neighborhood: 'La Dreta de l’Eixample', district: 'Eixample',
    tags: ['gaudi', 'modernismo'] },

  { slug: 'casa-amatller', name: 'Casa Amatller',
    officialUrl: 'https://amatller.org/',
    address: 'Passeig de Gràcia, 41, 08007 Barcelona',
    lat: 41.391389, lng: 2.164722, zipCode: '08007',
    neighborhood: 'La Dreta de l’Eixample', district: 'Eixample',
    tags: ['modernismo'] },

  { slug: 'casa-de-les-punxes', name: 'Casa de les Punxes',
    officialUrl: 'https://www.casadelespunxes.com/',
    address: 'Av. Diagonal, 420, 08037 Barcelona',
    lat: 41.397222, lng: 2.163889, zipCode: '08037',
    neighborhood: 'La Dreta de l’Eixample', district: 'Eixample',
    tags: ['modernismo'] },

  { slug: 'fundacio-antoni-tapies', name: 'Fundació Antoni Tàpies',
    officialUrl: 'https://fundaciotapies.org/',
    address: 'Carrer d’Aragó, 255, 08007 Barcelona',
    lat: 41.391389, lng: 2.163333, zipCode: '08007',
    neighborhood: 'La Dreta de l’Eixample', district: 'Eixample',
    tags: ['arte-contemporaneo'] },

  { slug: 'museu-egipci-de-barcelona', name: 'Museu Egipci de Barcelona',
    officialUrl: 'https://www.museuegipci.com/',
    address: 'Carrer de València, 284, 08007 Barcelona',
    lat: 41.392500, lng: 2.163611, zipCode: '08007',
    neighborhood: 'La Dreta de l’Eixample', district: 'Eixample',
    tags: ['arqueologia', 'egipto'] },

  { slug: 'museu-del-modernisme-de-barcelona', name: 'Museu del Modernisme de Barcelona',
    officialUrl: 'https://www.mmbcn.cat/',
    address: 'Carrer de Balmes, 48, 08007 Barcelona',
    lat: 41.390833, lng: 2.161667, zipCode: '08007',
    neighborhood: 'L’Antiga Esquerra de l’Eixample', district: 'Eixample',
    tags: ['modernismo'] },

  { slug: 'museu-del-perfum', name: 'Museu del Perfum',
    officialUrl: 'https://www.museudelperfum.com/',
    address: 'Passeig de Gràcia, 39, 08007 Barcelona',
    lat: 41.391111, lng: 2.164722, zipCode: '08007',
    neighborhood: 'La Dreta de l’Eixample', district: 'Eixample',
    tags: ['coleccion'] },

  { slug: 'fundacio-mapfre-casa-garriga-nogues', name: 'Fundación MAPFRE · Casa Garriga Nogués',
    officialUrl: 'https://www.fundacionmapfre.org/arte-y-cultura/sedes/barcelona-casa-garriga-nogues/',
    address: 'Carrer de la Diputació, 250, 08007 Barcelona',
    lat: 41.389444, lng: 2.166389, zipCode: '08007',
    neighborhood: 'La Dreta de l’Eixample', district: 'Eixample',
    tags: ['exposiciones', 'fotografia'] },

  { slug: 'museu-de-la-musica-de-barcelona', name: 'Museu de la Música de Barcelona',
    officialUrl: 'https://ajuntament.barcelona.cat/museumusica/',
    address: 'Carrer de Lepant, 150, 08013 Barcelona',
    lat: 41.398611, lng: 2.184722, zipCode: '08013',
    neighborhood: 'El Fort Pienc', district: 'Eixample',
    tags: ['musica'] },

  { slug: 'palau-robert', name: 'Palau Robert',
    officialUrl: 'https://palaurobert.gencat.cat/',
    address: 'Passeig de Gràcia, 107, 08008 Barcelona',
    lat: 41.394167, lng: 2.160556, zipCode: '08008',
    neighborhood: 'La Dreta de l’Eixample', district: 'Eixample',
    tags: ['exposiciones', 'gratis'] },

  { slug: 'recinte-modernista-de-sant-pau', name: 'Recinte Modernista de Sant Pau',
    officialUrl: 'https://www.santpaubarcelona.org/',
    address: 'Carrer de Sant Antoni Maria Claret, 167, 08025 Barcelona',
    lat: 41.411944, lng: 2.174444, zipCode: '08025',
    neighborhood: 'El Guinardó', district: 'Horta-Guinardó',
    tags: ['modernismo', 'arquitectura'] },

  // ── Sants-Montjuïc ──────────────────────────────────────────────────────
  { slug: 'mnac-museu-nacional-art-de-catalunya', name: 'MNAC · Museu Nacional d’Art de Catalunya',
    officialUrl: 'https://www.museunacional.cat/',
    address: 'Parc de Montjuïc, s/n, 08038 Barcelona',
    lat: 41.368333, lng: 2.153611, zipCode: '08038',
    neighborhood: 'El Poble-sec', district: 'Sants-Montjuïc',
    tags: ['arte', 'romanico'] },

  { slug: 'fundacio-joan-miro', name: 'Fundació Joan Miró',
    officialUrl: 'https://www.fmirobcn.org/',
    address: 'Parc de Montjuïc, s/n, 08038 Barcelona',
    lat: 41.368611, lng: 2.160000, zipCode: '08038',
    neighborhood: 'El Poble-sec', district: 'Sants-Montjuïc',
    tags: ['arte', 'miro'] },

  { slug: 'caixaforum-barcelona', name: 'CaixaForum Barcelona',
    officialUrl: 'https://caixaforum.org/es/barcelona',
    address: 'Av. de Francesc Ferrer i Guàrdia, 6-8, 08038 Barcelona',
    lat: 41.371389, lng: 2.149722, zipCode: '08038',
    neighborhood: 'El Poble-sec', district: 'Sants-Montjuïc',
    tags: ['exposiciones', 'modernismo'] },

  { slug: 'museu-arqueologia-de-catalunya', name: 'Museu d’Arqueologia de Catalunya',
    officialUrl: 'https://www.macbarcelona.cat/',
    address: 'Passeig de Santa Madrona, 39-41, 08038 Barcelona',
    lat: 41.367222, lng: 2.157222, zipCode: '08038',
    neighborhood: 'El Poble-sec', district: 'Sants-Montjuïc',
    tags: ['arqueologia'] },

  { slug: 'museu-etnologic-de-barcelona', name: 'Museu Etnològic i de Cultures del Món (Montjuïc)',
    officialUrl: 'https://ajuntament.barcelona.cat/museuetnologic/',
    address: 'Passeig de Santa Madrona, 16-22, 08038 Barcelona',
    lat: 41.367778, lng: 2.155278, zipCode: '08038',
    neighborhood: 'El Poble-sec', district: 'Sants-Montjuïc',
    tags: ['etnografia'] },

  { slug: 'museu-olimpic-i-de-lesport', name: 'Museu Olímpic i de l’Esport Joan Antoni Samaranch',
    officialUrl: 'https://www.museuolimpicbcn.cat/',
    address: 'Av. de l’Estadi, 60, 08038 Barcelona',
    lat: 41.364722, lng: 2.154722, zipCode: '08038',
    neighborhood: 'La Marina del Prat Vermell', district: 'Sants-Montjuïc',
    tags: ['deporte', 'familiar'] },

  { slug: 'jardi-botanic-de-barcelona', name: 'Jardí Botànic de Barcelona',
    officialUrl: 'https://museuciencies.cat/visitans/jardi-botanic/',
    address: 'Carrer del Doctor Font i Quer, 2, 08038 Barcelona',
    lat: 41.362778, lng: 2.155000, zipCode: '08038',
    neighborhood: 'La Marina del Prat Vermell', district: 'Sants-Montjuïc',
    tags: ['naturaleza', 'jardin'] },

  // ── Les Corts i Sarrià-Sant Gervasi ─────────────────────────────────────
  { slug: 'museu-del-fc-barcelona', name: 'Museu del FC Barcelona',
    officialUrl: 'https://www.fcbarcelona.es/es/entradas/museo',
    address: 'C/ d’Arístides Maillol, 12, 08028 Barcelona',
    lat: 41.380833, lng: 2.122778, zipCode: '08028',
    neighborhood: 'La Maternitat i Sant Ramon', district: 'Les Corts',
    tags: ['deporte', 'futbol'] },

  { slug: 'fundacio-sunol', name: 'Fundació Suñol',
    officialUrl: 'https://www.fundaciosunol.org/',
    address: 'Carrer de Mejía Lequerica, 14, 08028 Barcelona',
    lat: 41.383056, lng: 2.121944, zipCode: '08028',
    neighborhood: 'La Maternitat i Sant Ramon', district: 'Les Corts',
    tags: ['arte-contemporaneo'] },

  { slug: 'reial-monestir-de-pedralbes', name: 'Reial Monestir de Santa Maria de Pedralbes',
    officialUrl: 'https://monestirpedralbes.barcelona/',
    address: 'Baixada del Monestir, 9, 08034 Barcelona',
    lat: 41.395833, lng: 2.112222, zipCode: '08034',
    neighborhood: 'Pedralbes', district: 'Les Corts',
    tags: ['gotico', 'historia'] },

  { slug: 'cosmocaixa-barcelona', name: 'CosmoCaixa Barcelona',
    officialUrl: 'https://cosmocaixa.org/es/',
    address: 'Carrer d’Isaac Newton, 26, 08022 Barcelona',
    lat: 41.410000, lng: 2.125556, zipCode: '08022',
    neighborhood: 'Sant Gervasi - La Bonanova', district: 'Sarrià-Sant Gervasi',
    tags: ['ciencia', 'familiar'] },

  { slug: 'torre-bellesguard', name: 'Torre Bellesguard · Antoni Gaudí',
    officialUrl: 'https://bellesguardgaudi.com/',
    address: 'Carrer de Bellesguard, 6-8, 08022 Barcelona',
    lat: 41.410000, lng: 2.129167, zipCode: '08022',
    neighborhood: 'Sant Gervasi - La Bonanova', district: 'Sarrià-Sant Gervasi',
    tags: ['gaudi', 'modernismo'] },

  { slug: 'vil-la-joana-muhba-verdaguer', name: 'Vil·la Joana · MUHBA Verdaguer',
    officialUrl: 'https://www.barcelona.cat/museuhistoria/es/muhba-vil-la-joana',
    address: 'Carretera de l’Església, 104, 08017 Barcelona',
    lat: 41.417500, lng: 2.088333, zipCode: '08017',
    neighborhood: 'Vallvidrera, el Tibidabo i les Planes', district: 'Sarrià-Sant Gervasi',
    tags: ['literatura', 'gratis'] },

  // ── Gràcia ──────────────────────────────────────────────────────────────
  { slug: 'casa-vicens', name: 'Casa Vicens',
    officialUrl: 'https://casavicens.org/',
    address: 'Carrer de les Carolines, 20-26, 08012 Barcelona',
    lat: 41.403611, lng: 2.150278, zipCode: '08012',
    neighborhood: 'Vila de Gràcia', district: 'Gràcia',
    tags: ['gaudi', 'modernismo'] },

  { slug: 'casa-museu-gaudi', name: 'Casa Museu Gaudí (Park Güell)',
    officialUrl: 'https://parkguell.barcelona/es/casa-museo-gaudi',
    address: 'Carretera del Carmel, 23A, 08024 Barcelona',
    lat: 41.414722, lng: 2.152778, zipCode: '08024',
    neighborhood: 'La Salut', district: 'Gràcia',
    tags: ['gaudi'] },

  // ── Sant Martí i Sant Andreu ────────────────────────────────────────────
  { slug: 'museu-del-disseny-de-barcelona', name: 'Museu del Disseny de Barcelona',
    officialUrl: 'https://ajuntament.barcelona.cat/museudeldisseny/',
    address: 'Plaça de les Glòries Catalanes, 37-38, 08018 Barcelona',
    lat: 41.403056, lng: 2.187500, zipCode: '08018',
    neighborhood: 'El Parc i la Llacuna del Poblenou', district: 'Sant Martí',
    tags: ['diseno', 'moda'] },

  { slug: 'museu-blau-ciencies-naturals', name: 'Museu Blau · Ciències Naturals',
    officialUrl: 'https://museuciencies.cat/',
    address: 'Plaça de Leonardo da Vinci, 4-5, 08019 Barcelona',
    lat: 41.410556, lng: 2.221389, zipCode: '08019',
    neighborhood: 'El Besòs i el Maresme', district: 'Sant Martí',
    tags: ['ciencia', 'familiar'] },

  { slug: 'museu-can-framis', name: 'Museu Can Framis · Fundació Vila Casas',
    officialUrl: 'https://www.fundaciovilacasas.com/es/museo/can-framis',
    address: 'Carrer de Roc Boronat, 116-126, 08018 Barcelona',
    lat: 41.402222, lng: 2.192778, zipCode: '08018',
    neighborhood: 'El Poblenou', district: 'Sant Martí',
    tags: ['arte-contemporaneo', 'pintura-catalana'] },

  { slug: 'colleccio-de-carrosses-funebres', name: 'Col·lecció de Carrosses Fúnebres',
    officialUrl: 'https://www.cbsa.cat/es/coleccion-de-carrozas-funebres/',
    address: 'Carrer de Sancho de Ávila, 2, 08018 Barcelona',
    lat: 41.400833, lng: 2.188889, zipCode: '08018',
    neighborhood: 'El Parc i la Llacuna del Poblenou', district: 'Sant Martí',
    tags: ['coleccion', 'gratis'] },

  { slug: 'fabra-i-coats-centre-dart', name: 'Fabra i Coats · Centre d’Art Contemporani',
    officialUrl: 'https://www.barcelona.cat/fabraicoats/centredart/',
    address: 'Carrer de Sant Adrià, 20, 08030 Barcelona',
    lat: 41.432778, lng: 2.188056, zipCode: '08030',
    neighborhood: 'Sant Andreu', district: 'Sant Andreu',
    tags: ['arte-contemporaneo', 'gratis'] },

  // ── Área metropolitana ──────────────────────────────────────────────────
  { slug: 'museu-de-badalona', name: 'Museu de Badalona',
    officialUrl: 'https://www.museudebadalona.cat/',
    address: 'Plaça de l’Assemblea de Catalunya, 1, 08911 Badalona',
    lat: 41.450278, lng: 2.246944, zipCode: '08911',
    municipality: 'badalona', district: 'Badalona',
    tags: ['arqueologia', 'romano'] },

  { slug: 'museu-de-lhospitalet', name: 'Museu de L’Hospitalet',
    officialUrl: 'https://www.museul-h.cat/',
    address: 'Carrer del Xipreret, 21, 08901 L’Hospitalet de Llobregat',
    lat: 41.359722, lng: 2.098333, zipCode: '08901',
    municipality: 'lhospitalet', district: 'L’Hospitalet de Llobregat',
    tags: ['historia-local'] },

  { slug: 'museu-torre-balldovina', name: 'Museu Torre Balldovina',
    officialUrl: 'https://www.gramenet.cat/temes/cultura/museu-torre-balldovina/',
    address: 'Plaça de Pau Casals, s/n, 08921 Santa Coloma de Gramenet',
    lat: 41.452500, lng: 2.211111, zipCode: '08921',
    municipality: 'santacoloma', district: 'Santa Coloma de Gramenet',
    tags: ['arqueologia', 'historia-local'] },

  { slug: 'museu-can-tinture', name: 'Museu Can Tinturé',
    officialUrl: 'https://www.museus.esplugues.cat/',
    address: 'Carrer de l’Església, 36, 08950 Esplugues de Llobregat',
    lat: 41.377222, lng: 2.086944, zipCode: '08950',
    municipality: 'esplugues', district: 'Esplugues de Llobregat',
    tags: ['ceramica'] },

  { slug: 'museu-agbar-de-les-aigues', name: 'Museu Agbar de les Aigües',
    officialUrl: 'https://www.museuagbar.com/',
    address: 'Carretera de Sant Boi, 4-6, 08940 Cornellà de Llobregat',
    lat: 41.349722, lng: 2.089444, zipCode: '08940',
    municipality: 'cornella', district: 'Cornellà de Llobregat',
    tags: ['ciencia', 'industria'] },
]
